// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSak5NmZt_FSh-bmWlvssLRFcT5Xp60R0',
    appId: '1:639982938216:web:4fab7a4d772d63452cf3dd',
    messagingSenderId: '639982938216',
    projectId: 'exercease-d82ad',
    authDomain: 'exercease-d82ad.firebaseapp.com',
    storageBucket: 'exercease-d82ad.firebasestorage.app',
    measurementId: 'G-4M05Z2YJ0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHHK9Dss9wXipc4S2FN5JhDKrwOL27V2M',
    appId: '1:639982938216:android:25c0def33142b4a12cf3dd',
    messagingSenderId: '639982938216',
    projectId: 'exercease-d82ad',
    storageBucket: 'exercease-d82ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjyOnKlcS_it4FGJ5A-q-sXbBnk3IG5qQ',
    appId: '1:639982938216:ios:835085d330738df72cf3dd',
    messagingSenderId: '639982938216',
    projectId: 'exercease-d82ad',
    storageBucket: 'exercease-d82ad.firebasestorage.app',
    androidClientId: '639982938216-4ojvkuavslle5v6g6hqtn77ahelssgpq.apps.googleusercontent.com',
    iosClientId: '639982938216-jhdv9975vi83ksbj4bep5eqaduis58fp.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjyOnKlcS_it4FGJ5A-q-sXbBnk3IG5qQ',
    appId: '1:639982938216:ios:835085d330738df72cf3dd',
    messagingSenderId: '639982938216',
    projectId: 'exercease-d82ad',
    storageBucket: 'exercease-d82ad.firebasestorage.app',
    androidClientId: '639982938216-4ojvkuavslle5v6g6hqtn77ahelssgpq.apps.googleusercontent.com',
    iosClientId: '639982938216-jhdv9975vi83ksbj4bep5eqaduis58fp.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSak5NmZt_FSh-bmWlvssLRFcT5Xp60R0',
    appId: '1:639982938216:web:173958c53d0be2772cf3dd',
    messagingSenderId: '639982938216',
    projectId: 'exercease-d82ad',
    authDomain: 'exercease-d82ad.firebaseapp.com',
    storageBucket: 'exercease-d82ad.firebasestorage.app',
    measurementId: 'G-T49D6NK681',
  );

}